# Generated by Django 3.1.7 on 2021-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballer', '0003_auto_20210301_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='team',
            field=models.TextField(max_length=50, null=True, verbose_name='Takım Adı'),
        ),
    ]
