# Generated by Django 3.1.7 on 2021-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballer', '0004_footballer_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='team',
            field=models.CharField(max_length=50, null=True, verbose_name='Takım Adı'),
        ),
    ]
