# Generated by Django 3.1.7 on 2021-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballteam', '0002_auto_20210301_1342'),
        ('footballer', '0005_auto_20210302_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='teamName',
            field=models.CharField(max_length=50, null=True, verbose_name='Takım Adı'),
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='team',
        ),
        migrations.AddField(
            model_name='footballer',
            name='team',
            field=models.ManyToManyField(to='footballteam.FootballTeam'),
        ),
    ]
