# Generated by Django 3.1.7 on 2021-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballteam', '0002_auto_20210301_1342'),
        ('footballer', '0006_auto_20210302_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballer',
            name='teamName',
        ),
        migrations.AlterField(
            model_name='footballer',
            name='team',
            field=models.ManyToManyField(null=True, to='footballteam.FootballTeam', verbose_name='Takım'),
        ),
    ]
